"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs/promises"),os=require("node:os"),path=require("node:path"),test=require("node:test");
const {TaskStore}=require("./task-store.js");const {TaskEndService}=require("./task-end-service.js");
const base={teams:[]},changed={teams:[{id:"t1"}]};
async function fixture(lifecycle,{modified=false,pr=false,merged=false}={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),"ops-end-")),workspace=path.join(root,"w");await fs.mkdir(path.join(workspace,"public"),{recursive:true});await fs.writeFile(path.join(workspace,"public","data.json"),JSON.stringify(modified?changed:base));const store=new TaskStore({workspaceRoot:workspace,runtimeRoot:path.join(root,"r")});await store.initialize();let s=await store.createTask({lifecycleState:lifecycle});if(modified){s=(await store.saveBaseline(s.taskId,s.documentRevision,base,"sha256:x")).state;s=await store.updateState(s.taskId,s.documentRevision,d=>{d.execution.workspaceCandidateSha256="sha256:c";return d;});}if(pr)s=await store.updateState(s.taskId,s.documentRevision,d=>{d.submission={prUrl:"https://pr/1",status:"PR_CREATED"};return d;});const calls=[];const end=new TaskEndService({taskStore:store,workspaceRoot:workspace,run:(f,a)=>{calls.push([f,a]);if(a[1]==="view")return JSON.stringify({mergedAt:merged?"now":null});return "";}});return{store,s,workspace,calls,end,cleanup:()=>fs.rm(root,{recursive:true,force:true})};}
test("确认前取消直接结束且幂等",async t=>{const e=await fixture("AWAITING_CONFIRMATION");t.after(e.cleanup);let r=await e.end.end(e.s.taskId);assert.equal(r.state.lifecycle.state,"ENDED");r=await e.end.end(e.s.taskId);assert.equal(r.idempotent,true);});
test("修改后取消恢复 baseline",async t=>{const e=await fixture("VALIDATED",{modified:true});t.after(e.cleanup);const r=await e.end.end(e.s.taskId);assert.equal(r.state.lifecycle.state,"ENDED");assert.deepEqual(JSON.parse(await fs.readFile(path.join(e.workspace,"public/data.json"))),base);});
test("PR 后取消关闭 PR 并恢复 workspace",async t=>{const e=await fixture("PR_CREATED",{modified:true,pr:true});t.after(e.cleanup);await e.end.end(e.s.taskId);assert.ok(e.calls.some(([,a])=>a[1]==="close"));assert.deepEqual(JSON.parse(await fs.readFile(path.join(e.workspace,"public/data.json"))),base);});
test("已合并只清理不回滚",async t=>{const e=await fixture("MERGED",{modified:true,pr:true,merged:true});t.after(e.cleanup);await e.end.end(e.s.taskId);assert.deepEqual(JSON.parse(await fs.readFile(path.join(e.workspace,"public/data.json"))),changed);});
test("重启恢复把未知 pendingEffect 标为 ERROR",async t=>{const e=await fixture("SUBMITTING");t.after(e.cleanup);let s=await e.store.readTask(e.s.taskId);await e.store.updateState(s.taskId,s.documentRevision,d=>{d.control.pendingEffect={kind:"UNKNOWN_EFFECT"};return d;});const [r]=await e.end.recoverAll();assert.equal(r.kind,"error");assert.equal(r.state.lifecycle.state,"ERROR");});
